# SPDX-FileCopyrightText: 2026 Gabriel Santos de Souza <gabriel.santosdesouza@dcomp.ufs.br>
#
# SPDX-License-Identifier: GPL-3.0-or-later

SPDX-PackageName = "blog"
version = 1
[[annotations]]
  path = "**"
  precedence = "aggregate"
  SPDX-FileCopyrightText = "2026 Gabriel Santos de Souza <gabriel.santosdesouza@dcomp.ufs.br>"
  SPDX-License-Identifier = "GPL-3.0-or-later"
[[annotations]]
  path = ["content/"]
  precedence = "aggregate"
  SPDX-FileCopyrightText = "2026 Gabriel Santos de Souza <gabriel.santosdesouza@dcomp.ufs.br>"
  SPDX-License-Identifier = "CC-BY-4.0"
